# What's a tensor?

### Tensor Manipulation

An short introduction about PyTorch and about the chosen functions. 
- torch.Tensor.tolist()
- torch.rand()
- torch.Tensor.transpose()
- tensor.Tensor.view()
- tensor.Tensor.squeeze()

In [29]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor.tolist()

When we create tensor from list, we can transfer from tensor to list.

In [44]:
# Example 1

list_ex = [[3,4],[5,6]]
tensor_ex = torch.tensor(list_ex)
print(tensor_ex)

list_ret = tensor_ex.tolist()
print(list_ret)
print(list_ex == list_ret)

tensor([[3, 4],
        [5, 6]])
[[3, 4], [5, 6]]
True


In [48]:
# Example 2

list_ex = [[5,6],[7,8]]
tensor_ex = torch.tensor(list_ex)
print(tensor_ex)

list_ret = tensor_ex.tolist()
print(list_ret)
print(list_ex == list_ret)

tensor([[5, 6],
        [7, 8]])
[[5, 6], [7, 8]]
True


Explanation about example

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
list_ex = [[5,6],7]
tensor_ex = torch.tensor(list_ex)
print(tensor_ex)

list_ret = tensor_ex.tolist()
print(list_ret)
print(list_ex == list_ret)

TypeError: not a sequence

This example occurs error because tensor format is not adequate. Although we would like to handle list data structure, those tensor should be followed rule of tensor format.

Closing comments about when to use this function

## Function 2 - torch.rand()

torch.rand(formatofTensor) - Generate random value between 0 and 1.
if you'd like to get random integer then torch.randint(MIN, MAX, formatofTensor)



In [54]:
# Example 1
random = torch.randn(4,1)
print(random)

tensor([[-1.1263],
        [-1.9950],
        [-0.2004],
        [ 0.1084]])


In [60]:
# Example 2
random_1 = torch.randint(0,2,(3,))
print(random_1)


tensor([0, 1, 1])


Generate integers between 0 to 2 formatting (3,)

In [61]:
# Example 3 - breaking (to illustrate when it breaks)
random_2 = torch.randint(0,4)
print(random_2)

TypeError: randint(): argument 'size' (position 2) must be tuple of ints, not int

We need to give tensorFormat to function

This should be useful when we need tensor with random number

## Function 3 - torch.transpose(tensor format)

Add some explanations

In [75]:
# Example 1

list_ex = [[3,4],[5,6]]
tensor_ex = torch.tensor(list_ex)
print(tensor_ex)
# tensor_ex_transpose = torch.transpose(tensor_ex)

x = tensor_ex.t()
print(x)

tensor([[3, 4],
        [5, 6]])
tensor([[3, 5],
        [4, 6]])


if you would like to use 2D tensor then use .t()

In [97]:
# Example 2
x = torch.randn(2,2)
print(x)

y = torch.transpose(x,0,1)
print(y)


tensor([[-1.1537, -0.0297],
        [ 0.3763, -0.4083]])
tensor([[-1.1537,  0.3763],
        [-0.0297, -0.4083]])


In [101]:
# Example 3 - breaking (to illustrate when it breaks)
print(x)
y = torch.transpose(x,2,0)
print(y)


tensor([[-1.1537, -0.0297],
        [ 0.3763, -0.4083]])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

index should validate tensor size

When you'd like to reshape tensor then use transpose.

## Function 4 - tensor.view(tensorFormat)


This function change size of tensor.

In [104]:
# Example 1 - working
x_tensor = torch.randn(2,2,3)
print(x_tensor)

changed_tensor = x_tensor.view(1,1,12)
print(changed_tensor)


tensor([[[ 0.1089, -0.1641, -0.2868],
         [ 1.2549, -1.5844,  1.3199]],

        [[ 1.5676,  0.7701, -0.3221],
         [ 0.8153,  0.6465,  0.2437]]])
tensor([[[ 0.1089, -0.1641, -0.2868,  1.2549, -1.5844,  1.3199,  1.5676,
           0.7701, -0.3221,  0.8153,  0.6465,  0.2437]]])


x_tensor size is 2*2*3 = 12 
we can change tensor to any format but equal to 12. 
e.g 1*1*12 = 12 || 3*2*2 = 12

In [106]:
# Example 2 
x_tensor = torch.randn(2,2,3)
print(x_tensor)

changed_tensor = x_tensor.view(1,1,1,1,1,1,1,12)
print(changed_tensor)


tensor([[[-0.6893, -1.9808,  0.9974],
         [-0.1635, -0.6242,  0.2442]],

        [[-1.4485, -0.5327, -0.4136],
         [ 1.4070, -1.1150,  1.3017]]])
tensor([[[[[[[[-0.6893, -1.9808,  0.9974, -0.1635, -0.6242,  0.2442, -1.4485,
               -0.5327, -0.4136,  1.4070, -1.1150,  1.3017]]]]]]]])


In [107]:
# Example 3 
x_tensor = torch.randn(2,2,3)
print(x_tensor)

changed_tensor = x_tensor.view(1,3,12)
print(changed_tensor)

tensor([[[-1.3844, -0.2043,  1.7440],
         [-1.5430,  0.4245, -0.0895]],

        [[ 0.4128,  1.1918, -0.5342],
         [ 0.4378,  0.0743, -1.3782]]])


RuntimeError: shape '[1, 3, 12]' is invalid for input of size 12

tensor size should match

## Function 5 - tensor.squeeze()

squeeze function remove dimention whose size is 1.

In [132]:
# Example 1
x_ex = torch.randn((1,2,2,1,1)) 
print(x_ex)
print(x.squeeze())


tensor([[[[[-1.0604]],

          [[-1.0957]]],


         [[[-0.9098]],

          [[-0.4528]]]]])
tensor([[-1.1537, -0.0297],
        [ 0.3763, -0.4083]])


In [135]:
# Example 2
x_ex = torch.randn((1,1,1,1,1)) 
print(x_ex)
print(x.squeeze())
print(x.squeeze().size())

tensor([[[[[0.5883]]]]])
tensor([[-1.1537, -0.0297],
        [ 0.3763, -0.4083]])
torch.Size([2, 2])


## Conclusion

Those of functions are to manipulate tensor

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [136]:
!pip install jovian --upgrade -q

In [137]:
import jovian

In [138]:
jovian.commit(filename="assgn1.ipynb")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "hong918kr/assgn1" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/hong918kr/assgn1


'https://jovian.ml/hong918kr/assgn1'